## This notebook merge all the csv files in the "data" folder

In [26]:
#libraries

import os
import glob
import pandas as pd

In [27]:

os.chdir("../data/4.countries")
file_extension = '.csv'
all_filenames = [i for i in glob.glob(f"*{file_extension}")]
print(f"These are all the .csv files that will be merged: {all_filenames}.")

These are all the .csv files that will be merged: ['China.csv', 'USA.csv'].

### merge all the csv

In [28]:
all_tweets = pd.concat([pd.read_csv(f) for f in all_filenames if not os.stat(f).st_size == 0])
all_tweets =pd.DataFrame(all_tweets)

# remove duplicates
all_tweets.drop_duplicates(subset='id',inplace=True)

all_tweets

/tmp/ipykernel_7472/2189702379.py:1: DtypeWarning: Columns (34,35,38) have mixed types.Specify dtype option on import or set low_memory=False.
  all_tweets = pd.concat([pd.read_csv(f) for f in all_filenames if not os.stat(f).st_size == 0])

,created_at,id,id_str,text,display_text_range,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,matching_rules,retweeted_status,extended_entities,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink,account,period,scopes
0,Fri Feb 21 23:38:56 +0000 2020,1231000383151116289,1231000383151116289,CGTN talked to W. Ian Lipkin of Columbia Unive...,"[0, 140]","<a href=""https://about.twitter.com/products/tw...",True,NaN,NaN,NaN,...,[{'tag': None}],NaN,NaN,NaN,NaN,NaN,NaN,CGTN,JanFeb2020,NaN
1,Fri Feb 21 23:20:00 +0000 2020,1230995615900934144,1230995615900934144,Spring always brings along a lively vibe satur...,"[0, 140]","<a href=""https://studio.twitter.com"" rel=""nofo...",True,NaN,NaN,NaN,...,[{'tag': None}],NaN,NaN,NaN,NaN,NaN,NaN,CGTN,JanFeb2020,NaN
2,Fri Feb 21 21:44:08 +0000 2020,1230971490407010305,1230971490407010305,"February means carnival in Brazil. This year, ...","[0, 140]","<a href=""https://about.twitter.com/products/tw...",True,NaN,NaN,NaN,...,[{'tag': None}],NaN,NaN,NaN,NaN,NaN,NaN,CGTN,JanFeb2020,NaN
3,Fri Feb 21 20:15:00 +0000 2020,1230949059462037504,1230949059462037504,China and the world has made great strides in ...,"[0, 140]","<a href=""https://about.twitter.com/products/tw...",True,NaN,NaN,NaN,...,[{'tag': None}],NaN,NaN,NaN,NaN,NaN,NaN,CGTN,JanFeb2020,NaN
4,Fri Feb 21 19:47:37 +0000 2020,1230942170200276992,1230942170200276992,RT @CGTNEurope: A fake news story about cases ...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,NaN,NaN,...,[{'tag': None}],{'created_at': 'Fri Feb 21 14:59:58 +0000 2020...,NaN,NaN,NaN,NaN,NaN,CGTN,JanFeb2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15899,Sun Sep 20 03:00:18 +0000 2020,1307514897362808838,1307514897362808838,Police clash with protesters at anti-lockdown ...,"[0, 93]","<a href=""https://trueanthem.com/"" rel=""nofollo...",False,NaN,NaN,NaN,...,[{'tag': None}],NaN,"{'media': [{'id': 1307514896150663169, 'id_str...",NaN,NaN,NaN,NaN,R,SeptOct2020,NaN
15901,Sun Sep 20 02:35:00 +0000 2020,1307508528756789248,1307508528756789248,ICYMI: Due to a pause in high-speed ferry traf...,"[0, 140]","<a href=""https://studio.twitter.com"" rel=""nofo...",True,NaN,NaN,NaN,...,[{'tag': None}],NaN,NaN,NaN,NaN,NaN,NaN,R,SeptOct2020,NaN
15902,Sun Sep 20 02:25:00 +0000 2020,1307506012157628417,1307506012157628417,"ICYMI: With no internet access at home, these ...","[0, 140]","<a href=""https://studio.twitter.com"" rel=""nofo...",True,NaN,NaN,NaN,...,[{'tag': None}],NaN,NaN,NaN,NaN,NaN,NaN,R,SeptOct2020,NaN
15904,Sun Sep 20 00:55:10 +0000 2020,1307483406347972610,1307483406347972610,Australia virus epicentre state says new cases...,"[0, 94]","<a href=""https://trueanthem.com/"" rel=""nofollo...",False,NaN,NaN,NaN,...,[{'tag': None}],NaN,"{'media': [{'id': 1307483404879921152, 'id_str...",NaN,NaN,NaN,NaN,R,SeptOct2020,NaN
15905,Sun Sep 20 00:00:00 +0000 2020,1307469524749279232,1307469524749279232,ICYMI: A Hungarian orchestra conductor invents...,"[0, 140]","<a href=""https://studio.twitter.com"" rel=""nofo...",True,NaN,NaN,NaN,...,[{'tag': None}],NaN,NaN,NaN,NaN,NaN,NaN,R,SeptOct2020,NaN

### select only useful columns
Change cell below or don't execute it if you need different columns

In [29]:
all_tweets=all_tweets[['id_str','text']]
all_tweets

                    id_str                                               text
0      1231000383151116289  CGTN talked to W. Ian Lipkin of Columbia Unive...
1      1230995615900934144  Spring always brings along a lively vibe satur...
2      1230971490407010305  February means carnival in Brazil. This year, ...
3      1230949059462037504  China and the world has made great strides in ...
4      1230942170200276992  RT @CGTNEurope: A fake news story about cases ...
...                    ...                                                ...
15899  1307514897362808838  Police clash with protesters at anti-lockdown ...
15901  1307508528756789248  ICYMI: Due to a pause in high-speed ferry traf...
15902  1307506012157628417  ICYMI: With no internet access at home, these ...
15904  1307483406347972610  Australia virus epicentre state says new cases...
15905  1307469524749279232  ICYMI: A Hungarian orchestra conductor invents...

[20050 rows x 2 columns]

### Export as csv 
Note: the file is in the "src" folder in order to avoid to mess up with the files in the "data" folder

In [23]:
os.chdir("../../src")
all_tweets.to_csv('all_tweets.csv',index=False)